export const en = {
  brand: 'Aura',
  disclaimer: 'Aura is an AI companion, not a therapist or an emergency service.',
  chatDisclaimer: 'Aura is an AI companion, not a therapist or emergency service.',
  common: {
    back: 'Back', next: 'Next', cancel: 'Cancel', close: 'Close', save: 'Save', saved: 'Saved',
    copy: 'Copy', copied: 'Copied', delete: 'Delete', rename: 'Rename', done: 'Done', tryAgain: 'Try again',
    loading: 'One moment…', privacy: 'Privacy', terms: 'Terms', support: 'Get support now',
    somethingOff: 'Something went a little sideways. Your data is safe.',
  },
  support: {
    pill: 'Need support now?',
    title: "You're not alone in this",
    intro: "Whatever you're feeling right now, there are kind people ready to listen. Reaching out is a strong thing to do.",
    emergency: 'If you are in immediate danger, call your local emergency number.',
    call: 'Call', text: 'Text', visit: 'Visit website',
    countryLabel: 'Showing support for',
    intlTitle: 'Somewhere else?',
    intlBody: 'Find free, confidential helplines in your country.',
    intlLink: 'Open the international directory',
    inlineTitle: "You don't have to carry this alone. These people are ready to listen right now.",
    resultsCard: "Thank you for being honest with us. You deserve support that's more than an app. Here are people you can reach right now.",
    continueToChat: 'Continue to chat',
  },
  landing: {
    headline: 'A calm place to put everything down.',
    sub: 'Free, private emotional support that listens without judging. Available whenever you need it.',
    cta: 'Start talking',
    haveAccount: 'I already have an account',
    tiles: [
      { title: 'A check-in that gets you', body: 'A few gentle questions so Aura can meet you where you are.' },
      { title: 'Chats you can come back to', body: 'Pick up any conversation right where you left it.' },
      { title: 'Breathing space, one tap away', body: 'Guided breathing and grounding whenever things feel loud.' },
    ],
  },
  auth: {
    signupTitle: 'Make yourself at home',
    signupSub: 'It takes less than a minute.',
    loginTitle: 'Welcome back',
    loginSub: "It's good to see you again.",
    email: 'Email', password: 'Password', name: 'What should we call you?', nameHint: 'Optional',
    country: 'Where are you based?', countryHint: 'So we can show the right support lines.',
    countryPlaceholder: 'Choose your country',
    showPassword: 'Show password', hidePassword: 'Hide password',
    signup: 'Create my space', login: 'Log in', google: 'Continue with Google', or: 'or',
    toLogin: 'Already have an account? Log in', toSignup: 'New here? Create an account',
    badEmail: "That doesn't look like an email yet",
    shortPassword: 'A password needs at least 6 characters',
    needCountry: 'Please pick a country, even if it is approximate',
    failed: "We couldn't sign you in just now. Mind trying again?",
  },
  consent: {
    title: 'Before we begin',
    body: "Aura is here to listen, help you slow down, and think things through. A few quick things so we're on the same page.",
    age: "I'm 18 or older.",
    ai: 'I understand Aura is an AI companion, not a therapist, doctor, or emergency service.',
    adapt: "I'm okay with Aura adjusting how it talks to me based on my check-in and chats.",
    privacy: 'Read how we look after your data',
    cta: 'Continue',
    danger: "If you're in immediate danger, please contact local emergency services.",
    dangerLink: 'See support lines',
  },
  checkin: {
    header: 'About 4 minutes. There are no right answers.',
    promptWeek: 'Over the past week…',
    prompt2wk: 'Over the past two weeks…',
    preferNot: 'Prefer not to answer',
    saveLater: 'Save & finish later',
    skip: 'Skip for now',
    pauses: ["You're doing really well. Sip some water if you like.", "More than halfway there. Take a breath, there's no hurry."],
    safetyPause: "One last question, and it's an important one. Your honest answer helps Aura look after you better.",
    continue: 'Continue',
    finishing: 'Gathering your snapshot…',
    shortcut: 'Tip: press 1 to 4 to choose',
    progress: (n: number, total: number) => `Question ${n} of ${total}`,
  },
  weather: {
    title: 'Your emotional weather',
    sub: "This isn't a diagnosis. It's a gentle snapshot that helps Aura talk with you in the way that suits you best.",
    heaviness: 'What feels heavy',
    brightness: 'Brightness',
    brightnessHint: 'Moments of cheer, calm or contentment',
    cta: 'Start talking',
    retake: 'Retake the check-in',
    emptyTitle: 'No snapshot yet',
    emptyBody: 'Take the short check-in whenever you feel ready. It helps Aura support you better.',
    emptyCta: 'Take the check-in',
    bands: { low: 'quiet', mild: 'a little present', moderate: 'noticeable', high: 'heavy right now' },
    brightBands: { low: 'dim for now', mild: 'a few rays', moderate: 'fairly bright', high: 'shining' },
    dims: { stress: 'Stress', anxiety: 'Anxiety', low_mood: 'Low mood', anger: 'Anger', tiredness: 'Tiredness', grief: 'Grief', sadness: 'Sadness', brightness: 'Brightness' },
    taken: (d: string) => `From your check-in on ${d}`,
    history: 'Earlier check-ins',
    historyHint: 'Your weather over time, oldest on the left. Every sky changes.',
    latest: 'Latest',
  },
  shell: {
    newChat: 'New chat', search: 'Search your chats', emptyHistory: 'Your conversations will live here.',
    noMatches: 'No chats match that yet.',
    groups: { today: 'Today', yesterday: 'Yesterday', week: 'Previous 7 days', older: 'Older' },
    calm: 'Calm corner', weather: 'Your weather', settings: 'Settings', logout: 'Log out',
    openMenu: 'Open menu', closeMenu: 'Close menu', collapse: 'Collapse sidebar', expand: 'Expand sidebar',
    chatOptions: 'Chat options',
    deleteTitle: 'Delete this chat?', deleteBody: "This can't be undone.",
    defaultTitle: 'Quiet moment',
  },
  chat: {
    greeting: (name: string) => `Hi ${name}. No agenda here. What's on your mind?`,
    friend: 'there',
    chips: ['I need to vent', 'Help me calm down', "I can't sleep", 'I just want to chat'],
    placeholder: 'Write whatever is on your mind…',
    listening: 'Listening…',
    send: 'Send message', stop: 'Stop response',
    micStart: 'Start voice input', micStop: 'Stop voice input',
    micUnavailable: 'Voice needs microphone access. You can still type.',
    jump: 'Jump to latest',
    failed: "That didn't go through. Your words are safe. Try again?",
    retry: 'Retry',
    rest: 'Aura needs a little rest. You can come back soon, and the Calm corner is always open.',
    openCalm: 'Open Calm corner',
    breakTitle: "You've been here a while. Want to stretch, drink some water, or try a breathing minute?",
    breakAction: 'Try a breathing minute',
    dismiss: 'Dismiss',
    finishBanner: 'Want to finish your check-in? It helps Aura support you better.',
    finishCta: 'Finish check-in',
    tools: { breathing: 'Try a breathing minute', grounding: 'Try grounding' },
    thinking: 'Aura is thinking',
    loadFailed: "We couldn't open this chat just now.",
    counter: (n: number) => `${n} / 4000`,
  },
  calm: {
    title: 'Calm corner',
    sub: 'Small tools for loud moments. Nothing here is saved.',
    breathingTab: 'Guided breathing', groundingTab: '5-4-3-2-1 grounding',
    presets: { gentle: 'Gentle 4-6', box: 'Box 4-4-4-4' },
    inhale: 'Breathe in…', exhale: 'Breathe out…', hold: 'Hold…', ready: 'Ready when you are',
    start: 'Start', pause: 'Pause', resume: 'Resume', again: 'Go again',
    minutes: (n: number) => `${n} min`,
    complete: 'Nice. Notice how your shoulders feel.',
    groundingSteps: [
      'Name 5 things you can see',
      'Name 4 things you can feel',
      'Name 3 things you can hear',
      'Name 2 things you can smell',
      'Name 1 thing you can taste',
    ],
    groundingHint: 'Jot them down if it helps. This stays on your device.',
    groundingDone: "Well done. You're here, right now. Take one slow breath before you go on.",
    finish: 'Finish',
    sounds: {
      label: 'Night calm sounds',
      off: 'Quiet',
      rain: 'Soft rain',
      waves: 'Ocean waves',
      volume: 'Sound volume',
    },
  },
  settings: {
    title: 'Settings',
    profile: 'Profile', displayName: 'Display name', country: 'Country',
    appearance: 'Appearance', theme: 'Theme', themes: { light: 'Light', night: 'Soft night', system: 'System' },
    accent: 'Accent colour', textSize: 'Text size', sizes: { sm: 'S', md: 'M', lg: 'L' },
    voice: 'Voice', autoSend: 'Send automatically after I stop speaking',
    autoSendHint: "Off means your words land in the box so you can read them first.",
    voiceLanguage: 'Listening language',
    voiceLanguageHint: 'The language the mic listens for.',
    browserDefault: 'Same as my browser',
    data: 'Your data', retake: 'Retake check-in', download: 'Download my data',
    deleteChats: 'Delete all my chats', deleteAccount: 'Delete my account',
    deleteChatsTitle: 'Delete all your chats?', deleteChatsBody: "Every conversation will be gone for good. Your check-in and settings stay.",
    deleteAccountTitle: 'Delete your account?', deleteAccountBody: "This removes your chats, check-ins and profile permanently. We'll miss you, and you're always welcome back.",
    typeDelete: 'Type DELETE to confirm',
    legal: 'Legal',
    chatsDeleted: 'All chats deleted.',
    exported: 'Your data is downloading.',
  },
  legal: {
    privacyTitle: 'Privacy', termsTitle: 'Terms',
    placeholder: 'This page is a placeholder. The full policy will be published before launch.',
    home: 'Back to home',
  },
  errors: {
    title: 'Something went a little sideways',
    body: "It's not you. Let's try that again.",
  },
  accents: { apricot: 'Apricot', sage: 'Sage', lavender: 'Lavender', butter: 'Butter', sky: 'Sky' },
};

export const VOICE_LANGUAGES: { code: string; name: string }[] = [
  { code: 'en-US', name: 'English (US)' },
  { code: 'en-GB', name: 'English (UK)' },
  { code: 'en-IN', name: 'English (India)' },
  { code: 'en-AU', name: 'English (Australia)' },
  { code: 'hi-IN', name: 'हिन्दी (Hindi)' },
  { code: 'ta-IN', name: 'தமிழ் (Tamil)' },
  { code: 'bn-IN', name: 'বাংলা (Bengali)' },
  { code: 'es-ES', name: 'Español' },
  { code: 'fr-FR', name: 'Français' },
  { code: 'de-DE', name: 'Deutsch' },
  { code: 'pt-BR', name: 'Português (Brasil)' },
];

export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'US', name: 'United States' },
  { code: 'UK', name: 'United Kingdom' },
  { code: 'IN', name: 'India' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'IE', name: 'Ireland' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'INTL', name: 'Somewhere else' },
];
